Repository weDevsOfficial/wp-project-manager, pull requests merged in 2021-11, with the labels that each got.

#426 [i18n] Fix translation strings
  core/Notifications/Emails/New_Project_Notification.php
  core/User_Profile/Profile_Update.php
  languages/wedevs-project-manager.php
  views/assets/src/components/importtools/trello.vue
  views/assets/src/components/project-task-lists/new-task-form.vue
  views/assets/src/components/pusher/settings.vue
  views/assets/src/components/settings/new-task-type-form.vue
  views/assets/src/components/settings/pusher.vue
  views/assets/src/components/settings/task-type-item.vue
  views/assets/src/components/settings/task-types.vue
  views/emails/html/new-project.php
  views/emails/html/update-project.php
Labels: Ready to Merge

#427 Fixed Sanitization and escaping
  config/scripts.php
  core/Admin_Notice/Admin_Notice.php
  core/Cli/Commands.php
  core/Promotions/Offers.php
  core/Promotions/Promotions.php
  core/Router/WP_Router.php
  core/User_Profile/Profile_Update.php
  core/WP/Frontend.php
  core/WP/Output.php
  libs/configurations.php
  libs/functions.php
  src/Category/Sanitizers/Category_Sanitizer.php
  src/Project/Sanitizers/Project_Sanitizer.php
  src/Task/Sanitizers/Task_Sanitizer.php
  src/Task/Transformers/Task_Transformer.php
  views/assets/css/jquery-ui/images.zip
  views/assets/images/pm-logo-pro.png
  views/assets/src/components/my-tasks/directives.js
  views/assets/src/components/project-files/files.vue
  views/assets/src/components/project-overview/directive.js
  views/assets/src/helpers/less/icomoon.zip
  views/assets/vendor/chart/chart-datalabels.min.js
  views/assets/vendor/chart/chart.js
  views/assets/vendor/chart/chart.min.js
  views/emails/html/complete-task.php
  views/emails/html/footer.php
  views/emails/html/new-comment.php
  views/emails/html/new-message.php
  views/emails/html/new-project.php
  views/emails/html/new-task.php
  views/emails/html/update-comment.php
  views/emails/html/update-message.php
  views/emails/html/update-project.php
  views/emails/html/update-task.php
Labels: QA Approved, Ready to Merge

#398 Update Task_Controller.php
  src/Task/Controllers/Task_Controller.php
Labels: Needs Author Reply
